# Generated by Django 3.2 on 2023-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='full_name',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
